// ===================================
// 📋 LISTA DE EQUIPAMENTOS DISPONÍVEIS
// ===================================
// Lista extraída automaticamente da planilha atualizada
// Última atualização: 08/01/2026
// Total: 130 equipamentos

export const EQUIPAMENTOS = [
  "BC91",
  "CH 21",
  "CNC Fiber Laser AL1530F",
  "Central de Exaustão Immergut",
  "Centro 5º eixo",
  "Centro HB611GXS",
  "Centro Versa 4º eixo",
  "Centro de Furação CNC",
  "Centro de Furação HB611G",
  "Centro de Furação HB621G",
  "Centro de Furação M6",
  "Centro de Furação M6.5",
  "Centro de Furação M6.7",
  "Centro de Furação M6.8",
  "Centro de Furação Point 2",
  "Centro de Furação Vitap",
  "Centro de Usinagem Masterwood",
  "Centro de Usinagem Mitika",
  "Centro de Usinagem Poker",
  "Classic 21",
  "Coladeira Adamik",
  "Coladeira Bend",
  "Coladeira Falcon",
  "Coladeira Starwood HD623JPKQ",
  "Coladeira T300 Tecmatic",
  "Coladeira Verry",
  "Coladeira de Bordos 45com arredondador",
  "Coladeira de Bordos Astra",
  "Coladeira de Bordos Astra 30",
  "Coladeira de Bordos Astra 45",
  "Coladeira de Bordos Astra Bumerangue",
  "Coladeira de Bordos CH17",
  "Coladeira de Bordos CH21",
  "Coladeira de Bordos Century 5GS",
  "Coladeira de Bordos Falcon",
  "Coladeira de Bordos Millenium 6GS",
  "Coladeira de Bordos Prime 4GS",
  "Coladeira de Bordos Ultimate",
  "Coladeira de Bordos Vectra",
  "Coladeira de bordos Astra + R",
  "Coladeira de bordos BC92",
  "Coladeira de bordos Ultimate",
  "Coladeira de bordos Vectra",
  "Coladeira de bordos Vectra com PUR",
  "Coladeira de bordos Verry",
  "Coletores de pó",
  "Compressor Parafuso",
  "Contour 2.0",
  "Contour 2.0 Plus",
  "Contour S Line",
  "Contour S line",
  "Corte Laser tubos",
  "Célula Nesting 5º eixo",
  "Eclipse",
  "Embaladora Strech",
  "Embaladora Strech Immergut",
  "Emendadora de Lâminas",
  "Esquadrejadeira MJ 1132",
  "Esteira Retorno para Coladora de Brodo",
  "Furadeira Horizontal CNC",
  "Furadeira Múltipla Lidear",
  "Gerador Alta Frequência + Prensa 3D",
  "Guilhotina MQJ320A",
  "Juntadeira de lâminas",
  "Kit Prensa HFPB 1608 CH",
  "Laser chapa e tubo",
  "Linha Dupla de Furação Automática",
  "Linha Nesting Master V1",
  "Linha Nesting Master V2",
  "Linha de Prensa Auyu",
  "Lixadeira Banda Larga",
  "Millenium 6GS",
  "Nesting 3020 Marchiori",
  "Nesting CNC",
  "Nesting CNC (Over)",
  "Nesting CNC 2161 ATC",
  "Nesting CNC 3020 ATC-LE",
  "Nesting CNC CutPro",
  "Nesting CNC CutPro Elite",
  "Nesting CNC CutPro Plus",
  "Nesting CNC RC3020-ATC",
  "Nesting CNC para canaletados",
  "Nesting Lexno",
  "Nesting Robust V1",
  "Nesting Robust V1 com descarga",
  "Nesting Robust V1 com etiquetagem",
  "Nesting Robust V2",
  "Nesting SPL 3020",
  "Nesting3020 Marchiori",
  "NestingHold HE710GA",
  "Point 1",
  "Point 2",
  "Point 2 TPA",
  "Prensa Chancsmac",
  "Prensa HFPB 2010",
  "Prensa OMC",
  "Prensa Térmica 3013 2PM",
  "Prensa Térmica 3013 3PM",
  "Prensa Térmica 3013 4PM",
  "Prensa Térmica 3513 3PM",
  "Prensa Térmica 3516 2PM",
  "Prensa Térmica 4013 2PM",
  "Prensa Térmica 4016 2PM",
  "Prensa Térmica 4016 3PM",
  "Prensa Térmica 4016 4PM",
  "Prime 4GS",
  "Return Conveyor",
  "Roundern",
  "Router",
  "Router CNC",
  "Router CNC LE",
  "SPL 3020",
  "SVP 133",
  "SVP 145",
  "SVP 145 Plus",
  "SVP 145 Revisada",
  "SVP 420 Revisada",
  "Seccionadora 3400 CVL",
  "Seccionadora AXO 200",
  "Seccionadora CVL 3400",
  "Seccionadora Giben SP 90 (Barros)",
  "Seccionadora HP290",
  "Seccionadora Horizontal",
  "Seccionadora Mecânica",
  "Seccionadora SVP 145",
  "Serra de Fita CNC",
  "Solda a Laser Roclas",
  "Triturador Immergut",
  "Univer 620",
  "Vitap BC 92"
]

export default EQUIPAMENTOS
